sge-master/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('suppliers.urls')),    
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('products.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('embeddeds.urls')),
]

sge-master/brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

sge-master/inflows/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from . import models, forms, serializers


class InflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 10
    permission_required = 'inflows.view_inflow'

    def get_queryset(self):
        queryset = super().get_queryset()
        product = self.request.GET.get('product')

        if product:
            queryset = queryset.filter(product__title__icontains=product)

        return queryset


class InflowCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Inflow
    template_name = 'inflow_create.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')
    permission_required = 'inflows.add_inflow'


class InflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'
    permission_required = 'inflows.view_inflow'


class InflowCreateListAPIView(generics.ListCreateAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer


class InflowRetrieveAPIView(generics.RetrieveAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer

sge-master/app/templates/components/_ai_result.html
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo"
        aria-expanded="false" aria-controls="collapseTwo">
        SGE Agent
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        {{ ai_result|linebreaks }}
      </div>
    </div>
  </div>
</div>

sge-master/app/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <span class="text-muted">© 2025 Nectartec Embedded</span>
  </div>
</footer>

sge-master/app/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="{% url 'home' %}">Sistema de Gestão de Estoque (SGE)</a>
  </div>
</nav>

sge-master/app/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Primeira
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Anterior
          </a>
        </li>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Próxima
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Última
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

sge-master/app/templates/components/_product_metrics.html
<div class="card mt-4">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="card bg-primary">
          <div class="card-body">
            <h5 class="card-title">Quantidade de produtos</h5>
            <p class="card-text text-white font-weight-bold display-6">{{ product_metrics.total_quantity }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-danger">
          <div class="card-body">
            <h5 class="card-title">Custo do estoque</h5>
            <p class="card-text text-white font-weight-bold display-6">R$ {{ product_metrics.total_cost_price }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-success">
          <div class="card-body">
            <h5 class="card-title">Valor do estoque</h5>
            <p class="card-text text-white font-weight-bold display-6">R$ {{ product_metrics.total_selling_price }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-warning">
          <div class="card-body">
            <h5 class="card-title">Lucro do estoque</h5>
            <p class="card-text text-white font-weight-bold display-6">R$ {{ product_metrics.total_profit }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

sge-master/app/templates/components/_sales_metrics.html
<div class="card mt-4">
  <div class="card-body">
    <div class="row">
      <div class="col-md-3">
        <div class="card bg-primary">
          <div class="card-body">
            <h5 class="card-title">Quantidade de vendas</h5>
            <p class="card-text text-white font-weight-bold display-6">{{ sales_metrics.total_sales }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-danger">
          <div class="card-body">
            <h5 class="card-title">Produtos vendidos</h5>
            <p class="card-text text-white font-weight-bold display-6">{{ sales_metrics.total_products_sold }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-success">
          <div class="card-body">
            <h5 class="card-title">Valor das vendas</h5>
            <p class="card-text text-white font-weight-bold display-6">R$ {{ sales_metrics.total_sales_value }}</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card bg-warning">
          <div class="card-body">
            <h5 class="card-title">Lucro das vendas</h5>
            <p class="card-text text-white font-weight-bold display-6">R$ {{ sales_metrics.total_sales_profit }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

sge-master/app/templates/components/_sidebar.html
<div class="row flex-nowrap">
  <div class="col-auto col-md-0 col-xl-0 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white">
      <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
        <i class="bi bi-list fs-4"></i>
      </button>
      <div class="collapse d-sm-block" id="menuCollapse">
        <ul class="nav flex-column align-items-start" id="menu">
          <li>
            <a href="{% url 'home' %}" class="nav-link px-0 align-middle">
              <i class="bi bi-speedometer2 fs-4"></i>
              <span class="ms-1">Dashboard</span>
            </a>
          </li>
          {% if perms.suppliers.view_supplier %}
            <li>
              <a href="{% url 'supplier_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-truck fs-4"></i>
                <span class="ms-1">Fornecedores</span>
              </a>
            </li>
          {% endif %}
          {% if perms.embeddeds.view_embedded %}
            <li>
              <a href="{% url 'embedded_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-truck fs-4"></i>
                <span class="ms-1">Embedded</span>
              </a>
            </li>
          {% endif %}
          {% if perms.brands.view_brand %}
            <li>
              <a href="{% url 'brand_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-shop fs-4"></i>
                <span class="ms-1">Marcas</span>
              </a>
            </li>
          {% endif %}
          {% if perms.categories.view_category %}
            <li>
              <a href="{% url 'category_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-tags fs-4"></i>
                <span class="ms-1">Categorias</span>
              </a>
            </li>
          {% endif %}
          {% if perms.products.view_product %}
            <li>
              <a href="{% url 'product_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-box-seam fs-4"></i>
                <span class="ms-1">Produtos</span>
              </a>
            </li>
          {% endif %}
          {% if perms.inflows.view_inflow %}
            <li>
              <a href="{% url 'inflow_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-arrow-down-left-square fs-4"></i>
                <span class="ms-1">Entradas</span>
              </a>
            </li>
          {% endif %}
          {% if perms.outflows.view_outflow %}
            <li>
              <a href="{% url 'outflow_list' %}" class="nav-link px-0 align-middle">
                <i class="bi bi-arrow-up-right-square fs-4"></i>
                <span class="ms-1">Saídas</span>
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post" id="logout-form" class="nav-link px-0 align-middle">
              {% csrf_token %}
              <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                <span class="ms-1 align-middle">Sair</span>
              </button>
            </form>
            {% endif %}
          </li>
        </ul>
      </div>
      <hr>
    </div>
  </div>