sge-master - Copia/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('suppliers.urls')),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('products.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
]

sge-master - Copia/inflows/models.py
from django.db import models
from products.models import Product
from suppliers.models import Supplier


class Inflow(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name='inflows')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='inflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

sge-master - Copia/outflows/models.py
from django.db import models
from products.models import Product


class Outflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.product)

sge-master - Copia/app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="dark">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>

<body>
  {% include 'components/_header.html' %}

  <div class="container-fluid">
    {% if user.is_authenticated %}
      {% include 'components/_sidebar.html' %}
    {% endif %}

      <div class="col py-3">

        <div class="container mt-4">
          <main>
            {% block content %}
            {% endblock %}
          </main>
        </div>

      </div>
    </div>
  </div>
  {% include 'components/_footer.html' %}
</body>

</html>

sge-master - Copia/app/templates/home.html
{% extends 'base.html' %}

{% block title %}
    SGE - Home
{% endblock %}

{% block content %}

  {% include 'components/_ai_result.html' %}

  {% if perms.products.view_product and perms.inflows.view_inflow %}
    {% include 'components/_product_metrics.html' %}
  {% endif %}

  {% if perms.outflows.view_outflow %}
    {% include 'components/_sales_metrics.html' %}
  {% endif %}

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  {% if perms.outflows.view_outflow %}
    <div class="row mt-4 justify-content-center">
      <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Valor de vendas (Últimos 7 Dias)</h5>
        <canvas id="dailySalesChart"></canvas>
      </div>
      <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Quantidade de Vendas Diárias</h5>
        <canvas id="dailySalesQuantityChart"></canvas>
      </div>
      <script>
        document.addEventListener("DOMContentLoaded", function() {
          var dailySalesData = JSON.parse('{{ daily_sales_data|safe }}');
          var dailySalesQuantityData = JSON.parse('{{ daily_sales_quantity_data|safe }}');
    
          var ctxDailySales = document.getElementById('dailySalesChart').getContext('2d');
          var dailySalesChart = new Chart(ctxDailySales, {
            type: 'line',
            data: {
              labels: dailySalesData.dates,
              datasets: [{
                label: 'Valor em vendas',
                data: dailySalesData.values,
                fill: false,
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 2,
                tension: 0.5
              }]
            },
            options: {
              scales: {
                y: {
                  beginAtZero: true
                }
              }
            }
          });
    
          var ctxDailySalesQuantity = document.getElementById('dailySalesQuantityChart').getContext('2d');
          var dailySalesQuantityChart = new Chart(ctxDailySalesQuantity, {
            type: 'bar',
            data: {
              labels: dailySalesQuantityData.dates,
              datasets: [{
                label: 'Quantidade de Vendas',
                data: dailySalesQuantityData.values,
                backgroundColor: 'rgba(255, 99, 132, 0.6)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1
              }]
            },
            options: {
              scales: {
                y: {
                  beginAtZero: true
                }
              }
            }
          });
        });
      </script>
    </div>
  {% endif %}

  {% if perms.products.view_product %}
    <div class="row mt-5 justify-content-center">
      <div class="col-md-6 text-center">
        {% if product_count_by_category != '{}' %}
          <h5 class="mb-3">Produtos por Categoria</h5>
          <div class="mb-4"></div>
          <div class="embed-responsive embed-responsive-1by1" style="width: 400px; display: inline-block;">
            <canvas id="productByCategoryChart" class="embed-responsive-item"></canvas>
          </div>
        {% endif %}
      </div>
      <div class="col-md-6 text-center">
        {% if product_count_by_category != '{}' %}
          <h5 class="mb-3">Produtos por Marca</h5>
          <div class="mb-4"></div>
          <div style="width: 400px; display: inline-block;">
            <canvas id="productByBrandChart" class="embed-responsive-item"></canvas>
          </div>
        {% endif %}
      </div>
      <script>
        document.addEventListener("DOMContentLoaded", function() {  
          var productCountByCategory = JSON.parse('{{ product_count_by_category|safe }}');
          var productCountByBrand = JSON.parse('{{ product_count_by_brand|safe }}');
    
          var ctxCategory = document.getElementById('productByCategoryChart').getContext('2d');
          var productByCategoryChart = new Chart(ctxCategory, {
            type: 'doughnut',
            data: {
              labels: Object.keys(productCountByCategory),
              datasets: [{
                data: Object.values(productCountByCategory),
                borderWidth: 1
              }]
            },
            options: {
              plugins: {
                legend: {
                  display: false
                },
              }
            }
          });
    
          var ctxBrand = document.getElementById('productByBrandChart').getContext('2d');
          var productByBrandChart = new Chart(ctxBrand, {
            type: 'doughnut',
            data: {
              labels: Object.keys(productCountByBrand),
              datasets: [{
                data: Object.values(productCountByBrand),
                borderWidth: 1
              }]
            },
            options: {
              plugins: {
                legend: {
                  display: false
                },
              }
            }
          });
        });
      </script>
    </div>
  {% endif %}
{% endblock %}